---
version: "3"
services:
  
  pgadmin:
    image: dpage/pgadmin4
    logging:
      driver: none
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    depends_on:
      - postgres
    ports:
      - 6050:80

  postgres:
    image: postgres:16
    environment:
      - POSTGRES_DB=test_db
      - POSTGRES_PASSWORD=123456
      - POSTGRES_USER=rajesh

    volumes:
      - postgres-db:/var/lib/postgresql/data

  api:
    build: .
    depends_on:
      - postgres
    ports:
      - 3000:8000
    environment:
      - ".env"
    # command: "alembic upgrade head && uvicorn app.main:app --reload --port 5000 --host 0.0.0.0"
  
volumes:
  postgres-db: null
